root = "."

[build]
  bin = "main"
  pre_cmd=[
	"uglifyjs static/scripts/src.js --output static/scripts/src.min.js",
	"gzip -k static/scripts/src.min.js || true",
	"uglifycss static/icons.css --output static/icons.min.css",
	"gzip -k static/icons.min.css || true",
	"tailwindcss -i static/input.css -o static/output.css --minify",
	"gzip -k static/output.css || true",
  ]
  cmd = "go build -o main main.go"
  args_bin = ["-p", "test.md"]
  include_ext = ["go", "html", "css", "js"]
  exclude_file = ["static/icons.min.css", "static/output.css", "static/scripts/src.min.js"]

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  log = "white"
