CREATE TABLE IF NOT EXISTS posts (
    id INTEGER PRIMARY KEY,
    file_path TEXT UNIQUE NOT NULL,
    name TEXT UNIQUE NOT NULL,
    content TEXT NOT NULL,
    last_modified_time TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS tags (
    id INTEGER PRIMARY KEY,
    name TEXT UNIQUE NOT NULL
);
CREATE TABLE IF NOT EXISTS posts_tags (
    id INTEGER PRIMARY KEY,
    post_id INTEGER NOT NULL,
    tag_id INTEGER NOT NULL,
    FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE,
    FOREIGN KEY(tag_id) REFERENCES tags(id)ON DELETE CASCADE
);

